version: "3"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.local
    environment:
      - VITE_API_ROOT_ENDPOINT=${API_ROOT_ENDPOINT}
    ports:
      - 5173:5173
    volumes:
      - ./:/usr/src/newswaters-web/
    tty: true
    working_dir: /usr/src/newswaters-web/newswaters/
